/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
/**
 * A generic error response.
 */
export type ErrorResponseSchema = {
    /**
     * A description of the error.
     */
    detail: string;
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ModelContributionSelection = 'all' | 'personal' | 'work';

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};
