/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};
